version: '3.8'

services:
  frontend-teste:
    build: ./frontend/flaskmiddle
    command: >
      /bin/bash -c "NUM_WORKERS=$$((2 * $$(nproc) + 1)) &&
      gunicorn -b 0.0.0.0:${FRONTEND_PORT} --worker-class gevent --workers $$NUM_WORKERS --timeout 600 run:app"
    env_file:
      - ./.env
    depends_on:
      - backend-teste
    expose:
      - ${FRONTEND_PORT}
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    networks:
      - frontend-backend-net

#   celery_queries-teste:
#     build: ./backend
#     command: celery -A backend.worker.celery_start_queries worker --autoscale=30,15 -Q fila_queries --loglevel=info --without-heartbeat #--pool=gevent --loglevel=info -c 10 
#     env_file:
#       - ./.env
#     volumes:
#       - .:/app
#     depends_on:
# #      - db-teste
#       rabbitmq:
#         condition: service_healthy
#     networks:
#       - backend-net
#       - banco

  backend-teste:
    build: ./backend
    command: >
      /bin/bash -c "NUM_WORKERS=$$((2 * $$(nproc) + 1)) &&
      gunicorn backend.app.main:app --workers $$NUM_WORKERS --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:${BACKEND_PORT} --timeout 600"
    volumes:
      - .:/app
    env_file:
      - ./.env
    expose:
      - ${BACKEND_PORT}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
#      - db-teste
      - redis-teste
      - celery_tasks-teste
      - celery_despachante-teste
    networks:
      - backend-net
      - frontend-backend-net
 

  celery_tasks-teste:
    build: ./backend
    command: celery -A backend.worker.celery_start_tasks worker -Q fila_tasks -c 10
    env_file:
      - ./.env
    volumes:
      - .:/app
    depends_on:
#      - db-teste
      - redis-teste
    networks:
      - backend-net

  celery_despachante-teste:
    build: ./backend
    command: celery -A backend.worker.celery_start_despachante worker -Q fila_despachante --loglevel=info -c 10
    env_file:
      - ./.env
    volumes:
      - .:/app
    depends_on:
#      - db-teste
      - redis-teste
      - celery_tasks-teste
    networks:
      - backend-net