# version: '3'

services:
  # FastAPI Login
  api_login:
    build: ./backend
    command: >
      /bin/bash -c "uvicorn backend.app.api.api_login:app --host 0.0.0.0 --port 8002 --reload"
    volumes:
      - ./protos:/app/protos
    env_file:
      - ./.env
    # ports:
    #   - "8002:8002"
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_started
      redis:
        condition: service_started
    networks:
      - backend-net
      - frontend-backend-net

  api_login_ppgls:
    build: ./backend
    command: >
      /bin/bash -c "uvicorn backend.app.api.api_login_formulario:app --host 0.0.0.0 --port 8001 --reload"
    volumes:
      - ./protos:/app/protos
    env_file:
      - ./.env
    # ports:
    #   - "8001:8001"
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_started
      redis:
        condition: service_started
    networks:
      - backend-net
      - frontend-backend-net

  celery_queries_worker:
    build: ./backend
    command: celery -A backend.worker.celery_start_queries worker --pool=threads -c 4 -Q fila_queries -l INFO -n worker1@%h --events
    volumes:
      - ./protos:/app/protos/
    env_file:
      - ./.env
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_started
      redis:
        condition: service_started
    networks:
      - backend-net

  flower:
    image: mher/flower
    ports:
      - "8003:5555"
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672/vhost
    depends_on:
      - rabbitmq
      - celery_queries_worker
    restart: unless-stopped
    networks:
      - backend-net
  # Server PPG
  server_ppg:
    build: ./backend
    command: python backend/app/api/api.py
    volumes:
      - ./protos:/app/protos/
    env_file:
      - ./.env
    ports:
      - "${GRPC_SERVER_HOST}:${GRPC_SERVER_HOST}"
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_started
      redis:
        condition: service_started
    networks:
      - frontend-backend-net
      - backend-net

  # Server PPGLS
  server_ppgls:
    build: ./backend
    command: python backend/app/api/api_ppgls.py
    volumes:
      - ./protos:/app/protos/
    env_file:
      - ./.env
    ports:
      - "${GRPC_SERVER_PPGLS}:${GRPC_SERVER_PPGLS}"
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_started
      redis:
        condition: service_started
    networks:
      - frontend-backend-net
      - backend-net

  # Server GRAD
  server_grad:
    build: ./backend
    command: python backend/app/api/api_grad.py
    volumes:
      - ./protos:/app/protos/
    env_file:
      - ./.env
    ports:
      - "${GRPC_SERVER_GRAD}:${GRPC_SERVER_GRAD}"
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_started
      redis:
        condition: service_started
    networks:
      - frontend-backend-net
      - backend-net

  # Server USUARIOS
  server_usuarios:
    build: ./backend
    command: python backend/app/api/api_usuarios.py
    volumes:
      - ./protos:/app/protos/
    env_file:
      - ./.env
    ports:
      - "${GRPC_SERVER_USUARIOS}:${GRPC_SERVER_USUARIOS}"
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_started
      redis:
        condition: service_started
    networks:
      - frontend-backend-net
      - backend-net

  # Frontend Next.js
  frontend:
    build: ./frontend
    command: npm run dev
    # volumes:
    #   - ./frontend:/app
    ports:
      - "3002:3000"  # Porta padrão do Next.js
    networks:
      - frontend-backend-net

  # Redis
  redis:
    image: 'redis:latest'
    env_file:
      - ./.env
    # ports:
    #   - "${REDIS_PORT}:${REDIS_PORT}"
    networks:
      - backend-net

  # Banco de dados
  db:
    build: ./backend/db
    env_file:
      - ./.env
    environment:
    - POSTGRES_PORT=${POSTGRES_PORT}
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data
      - ./backend/db/tarrafaDB_2_tables.sql:/docker-entrypoint-initdb.d/tarrafaDB_2_tables.sql
      - ./backend/db/tarrafaDB_2_view_tables.sql:/docker-entrypoint-initdb.d/tarrafaDB_2_view_tables.sql
      - ./backend/db/tarrafaDB_2_formularios_tables.sql:/docker-entrypoint-initdb.d/tarrafaDB_2_formularios_tables.sql
      - ./backend/db/tarrafaDB_grad_tables.sql:/docker-entrypoint-initdb.d/tarrafaDB_grad_tables.sql
      - ./backup:/backup
    networks:
      - backend-net

  # PGAdmin
  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - ./.env
    environment:
      PGADMIN_DEFAULT_EMAIL: $PGADMIN_EMAIL
      PGADMIN_DEFAULT_PASSWORD: $PGADMIN_SENHA
    volumes:
      - ./backup:/backup
    ports:
      - "8008:80"
    restart: "no"
    networks:
      - backend-net

  rabbitmq:
    image: rabbitmq:management
    hostname: rabbitmq
    env_file:
      - ./.env
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=vhost
    ports:
      # - "8004:5672"
      - "8004:15672"
    volumes:
      - ./data/rabbitmq_data:/var/lib/rabbitmq/data
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 20s
      retries: 5
    networks:
      - backend-net

networks:
  frontend-backend-net:
  backend-net: