# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ppg.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tppg.proto\x12 backend.app.api.api_vi.endpoints\"4\n\nPpgRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04\x61noi\x18\x02 \x01(\x05\x12\x0c\n\x04\x61nof\x18\x03 \x01(\x05\"%\n\x07PpgJson\x12\x0c\n\x04nome\x18\x01 \x01(\t\x12\x0c\n\x04json\x18\x02 \x01(\t\"F\n\x0bPpgResponse\x12\x37\n\x04item\x18\x01 \x03(\x0b\x32).backend.app.api.api_vi.endpoints.PpgJson2~\n\x0bIndicadores\x12o\n\x10ObtemIndicadores\x12,.backend.app.api.api_vi.endpoints.PpgRequest\x1a-.backend.app.api.api_vi.endpoints.PpgResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ppg_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PPGREQUEST']._serialized_start=47
  _globals['_PPGREQUEST']._serialized_end=99
  _globals['_PPGJSON']._serialized_start=101
  _globals['_PPGJSON']._serialized_end=138
  _globals['_PPGRESPONSE']._serialized_start=140
  _globals['_PPGRESPONSE']._serialized_end=210
  _globals['_INDICADORES']._serialized_start=212
  _globals['_INDICADORES']._serialized_end=338
# @@protoc_insertion_point(module_scope)
