/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 4.25.5
 * source: grad.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./messages";
import * as grpc_1 from "@grpc/grpc-js";
export namespace protos {
    interface GrpcUnaryServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, metadata: grpc_1.Metadata, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
    }
    interface GrpcStreamServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): grpc_1.ClientReadableStream<R>;
        (message: P, options?: grpc_1.CallOptions): grpc_1.ClientReadableStream<R>;
    }
    interface GrpWritableServiceInterface<P, R> {
        (metadata: grpc_1.Metadata, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (metadata: grpc_1.Metadata, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
    }
    interface GrpcChunkServiceInterface<P, R> {
        (metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): grpc_1.ClientDuplexStream<P, R>;
        (options?: grpc_1.CallOptions): grpc_1.ClientDuplexStream<P, R>;
    }
    interface GrpcPromiseServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): Promise<R>;
        (message: P, options?: grpc_1.CallOptions): Promise<R>;
    }
    export abstract class UnimplementedIndicadoresGraduacaoService {
        static definition = {
            GetAbaIndicadoresCurso: {
                path: "/protos.IndicadoresGraduacao/GetAbaIndicadoresCurso",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_1.protos.GradRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_1.protos.GradRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_1.protos.GradResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_1.protos.GradResponse.deserialize(new Uint8Array(bytes))
            },
            GetAbaDisciplinas: {
                path: "/protos.IndicadoresGraduacao/GetAbaDisciplinas",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_1.protos.GradDisciplinasRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_1.protos.GradDisciplinasRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_1.protos.GradResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_1.protos.GradResponse.deserialize(new Uint8Array(bytes))
            },
            GetAbaEgressos: {
                path: "/protos.IndicadoresGraduacao/GetAbaEgressos",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_1.protos.GradRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_1.protos.GradRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_1.protos.GradResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_1.protos.GradResponse.deserialize(new Uint8Array(bytes))
            },
            GetAbaProfessores: {
                path: "/protos.IndicadoresGraduacao/GetAbaProfessores",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_1.protos.GradRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_1.protos.GradRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_1.protos.GradResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_1.protos.GradResponse.deserialize(new Uint8Array(bytes))
            },
            GetIndicadoresDisciplina: {
                path: "/protos.IndicadoresGraduacao/GetIndicadoresDisciplina",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_1.protos.GradDisciplinasRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_1.protos.GradDisciplinasRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_1.protos.GradResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_1.protos.GradResponse.deserialize(new Uint8Array(bytes))
            },
            GetIndicadoresGlobais: {
                path: "/protos.IndicadoresGraduacao/GetIndicadoresGlobais",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_1.protos.GradRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_1.protos.GradRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_1.protos.GradResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_1.protos.GradResponse.deserialize(new Uint8Array(bytes))
            }
        };
        [method: string]: grpc_1.UntypedHandleCall;
        abstract GetAbaIndicadoresCurso(call: grpc_1.ServerUnaryCall<dependency_1.protos.GradRequest, dependency_1.protos.GradResponse>, callback: grpc_1.sendUnaryData<dependency_1.protos.GradResponse>): void;
        abstract GetAbaDisciplinas(call: grpc_1.ServerUnaryCall<dependency_1.protos.GradDisciplinasRequest, dependency_1.protos.GradResponse>, callback: grpc_1.sendUnaryData<dependency_1.protos.GradResponse>): void;
        abstract GetAbaEgressos(call: grpc_1.ServerUnaryCall<dependency_1.protos.GradRequest, dependency_1.protos.GradResponse>, callback: grpc_1.sendUnaryData<dependency_1.protos.GradResponse>): void;
        abstract GetAbaProfessores(call: grpc_1.ServerUnaryCall<dependency_1.protos.GradRequest, dependency_1.protos.GradResponse>, callback: grpc_1.sendUnaryData<dependency_1.protos.GradResponse>): void;
        abstract GetIndicadoresDisciplina(call: grpc_1.ServerUnaryCall<dependency_1.protos.GradDisciplinasRequest, dependency_1.protos.GradResponse>, callback: grpc_1.sendUnaryData<dependency_1.protos.GradResponse>): void;
        abstract GetIndicadoresGlobais(call: grpc_1.ServerUnaryCall<dependency_1.protos.GradRequest, dependency_1.protos.GradResponse>, callback: grpc_1.sendUnaryData<dependency_1.protos.GradResponse>): void;
    }
    export class IndicadoresGraduacaoClient extends grpc_1.makeGenericClientConstructor(UnimplementedIndicadoresGraduacaoService.definition, "IndicadoresGraduacao", {}) {
        constructor(address: string, credentials: grpc_1.ChannelCredentials, options?: Partial<grpc_1.ChannelOptions>) {
            super(address, credentials, options);
        }
        GetAbaIndicadoresCurso: GrpcUnaryServiceInterface<dependency_1.protos.GradRequest, dependency_1.protos.GradResponse> = (message: dependency_1.protos.GradRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.protos.GradResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.protos.GradResponse>, callback?: grpc_1.requestCallback<dependency_1.protos.GradResponse>): grpc_1.ClientUnaryCall => {
            return super.GetAbaIndicadoresCurso(message, metadata, options, callback);
        };
        GetAbaDisciplinas: GrpcUnaryServiceInterface<dependency_1.protos.GradDisciplinasRequest, dependency_1.protos.GradResponse> = (message: dependency_1.protos.GradDisciplinasRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.protos.GradResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.protos.GradResponse>, callback?: grpc_1.requestCallback<dependency_1.protos.GradResponse>): grpc_1.ClientUnaryCall => {
            return super.GetAbaDisciplinas(message, metadata, options, callback);
        };
        GetAbaEgressos: GrpcUnaryServiceInterface<dependency_1.protos.GradRequest, dependency_1.protos.GradResponse> = (message: dependency_1.protos.GradRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.protos.GradResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.protos.GradResponse>, callback?: grpc_1.requestCallback<dependency_1.protos.GradResponse>): grpc_1.ClientUnaryCall => {
            return super.GetAbaEgressos(message, metadata, options, callback);
        };
        GetAbaProfessores: GrpcUnaryServiceInterface<dependency_1.protos.GradRequest, dependency_1.protos.GradResponse> = (message: dependency_1.protos.GradRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.protos.GradResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.protos.GradResponse>, callback?: grpc_1.requestCallback<dependency_1.protos.GradResponse>): grpc_1.ClientUnaryCall => {
            return super.GetAbaProfessores(message, metadata, options, callback);
        };
        GetIndicadoresDisciplina: GrpcUnaryServiceInterface<dependency_1.protos.GradDisciplinasRequest, dependency_1.protos.GradResponse> = (message: dependency_1.protos.GradDisciplinasRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.protos.GradResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.protos.GradResponse>, callback?: grpc_1.requestCallback<dependency_1.protos.GradResponse>): grpc_1.ClientUnaryCall => {
            return super.GetIndicadoresDisciplina(message, metadata, options, callback);
        };
        GetIndicadoresGlobais: GrpcUnaryServiceInterface<dependency_1.protos.GradRequest, dependency_1.protos.GradResponse> = (message: dependency_1.protos.GradRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.protos.GradResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.protos.GradResponse>, callback?: grpc_1.requestCallback<dependency_1.protos.GradResponse>): grpc_1.ClientUnaryCall => {
            return super.GetIndicadoresGlobais(message, metadata, options, callback);
        };
    }
    export abstract class UnimplementedDadosGraduacaoService {
        static definition = {
            GetCursos: {
                path: "/protos.DadosGraduacao/GetCursos",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_1.protos.GradRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_1.protos.GradRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_1.protos.GradResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_1.protos.GradResponse.deserialize(new Uint8Array(bytes))
            },
            GetCurso: {
                path: "/protos.DadosGraduacao/GetCurso",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_1.protos.GradRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_1.protos.GradRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_1.protos.GradResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_1.protos.GradResponse.deserialize(new Uint8Array(bytes))
            },
            GetDisciplinas: {
                path: "/protos.DadosGraduacao/GetDisciplinas",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_1.protos.GradDisciplinasRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_1.protos.GradDisciplinasRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_1.protos.GradResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_1.protos.GradResponse.deserialize(new Uint8Array(bytes))
            },
            GetDisciplina: {
                path: "/protos.DadosGraduacao/GetDisciplina",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_1.protos.GradDisciplinasRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_1.protos.GradDisciplinasRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_1.protos.GradResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_1.protos.GradResponse.deserialize(new Uint8Array(bytes))
            }
        };
        [method: string]: grpc_1.UntypedHandleCall;
        abstract GetCursos(call: grpc_1.ServerUnaryCall<dependency_1.protos.GradRequest, dependency_1.protos.GradResponse>, callback: grpc_1.sendUnaryData<dependency_1.protos.GradResponse>): void;
        abstract GetCurso(call: grpc_1.ServerUnaryCall<dependency_1.protos.GradRequest, dependency_1.protos.GradResponse>, callback: grpc_1.sendUnaryData<dependency_1.protos.GradResponse>): void;
        abstract GetDisciplinas(call: grpc_1.ServerUnaryCall<dependency_1.protos.GradDisciplinasRequest, dependency_1.protos.GradResponse>, callback: grpc_1.sendUnaryData<dependency_1.protos.GradResponse>): void;
        abstract GetDisciplina(call: grpc_1.ServerUnaryCall<dependency_1.protos.GradDisciplinasRequest, dependency_1.protos.GradResponse>, callback: grpc_1.sendUnaryData<dependency_1.protos.GradResponse>): void;
    }
    export class DadosGraduacaoClient extends grpc_1.makeGenericClientConstructor(UnimplementedDadosGraduacaoService.definition, "DadosGraduacao", {}) {
        constructor(address: string, credentials: grpc_1.ChannelCredentials, options?: Partial<grpc_1.ChannelOptions>) {
            super(address, credentials, options);
        }
        GetCursos: GrpcUnaryServiceInterface<dependency_1.protos.GradRequest, dependency_1.protos.GradResponse> = (message: dependency_1.protos.GradRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.protos.GradResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.protos.GradResponse>, callback?: grpc_1.requestCallback<dependency_1.protos.GradResponse>): grpc_1.ClientUnaryCall => {
            return super.GetCursos(message, metadata, options, callback);
        };
        GetCurso: GrpcUnaryServiceInterface<dependency_1.protos.GradRequest, dependency_1.protos.GradResponse> = (message: dependency_1.protos.GradRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.protos.GradResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.protos.GradResponse>, callback?: grpc_1.requestCallback<dependency_1.protos.GradResponse>): grpc_1.ClientUnaryCall => {
            return super.GetCurso(message, metadata, options, callback);
        };
        GetDisciplinas: GrpcUnaryServiceInterface<dependency_1.protos.GradDisciplinasRequest, dependency_1.protos.GradResponse> = (message: dependency_1.protos.GradDisciplinasRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.protos.GradResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.protos.GradResponse>, callback?: grpc_1.requestCallback<dependency_1.protos.GradResponse>): grpc_1.ClientUnaryCall => {
            return super.GetDisciplinas(message, metadata, options, callback);
        };
        GetDisciplina: GrpcUnaryServiceInterface<dependency_1.protos.GradDisciplinasRequest, dependency_1.protos.GradResponse> = (message: dependency_1.protos.GradDisciplinasRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.protos.GradResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.protos.GradResponse>, callback?: grpc_1.requestCallback<dependency_1.protos.GradResponse>): grpc_1.ClientUnaryCall => {
            return super.GetDisciplina(message, metadata, options, callback);
        };
    }
}
