/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 4.25.5
 * source: ppg.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./messages";
import * as grpc_1 from "@grpc/grpc-js";
export namespace protos {
    interface GrpcUnaryServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, metadata: grpc_1.Metadata, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
    }
    interface GrpcStreamServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): grpc_1.ClientReadableStream<R>;
        (message: P, options?: grpc_1.CallOptions): grpc_1.ClientReadableStream<R>;
    }
    interface GrpWritableServiceInterface<P, R> {
        (metadata: grpc_1.Metadata, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (metadata: grpc_1.Metadata, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
    }
    interface GrpcChunkServiceInterface<P, R> {
        (metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): grpc_1.ClientDuplexStream<P, R>;
        (options?: grpc_1.CallOptions): grpc_1.ClientDuplexStream<P, R>;
    }
    interface GrpcPromiseServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): Promise<R>;
        (message: P, options?: grpc_1.CallOptions): Promise<R>;
    }
    export abstract class UnimplementedPPGService {
        static definition = {
            ObtemInformacaoPPG: {
                path: "/protos.PPG/ObtemInformacaoPPG",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_1.protos.PpgRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_1.protos.PpgRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_1.protos.PpgResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_1.protos.PpgResponse.deserialize(new Uint8Array(bytes))
            },
            ObtemIndicadores: {
                path: "/protos.PPG/ObtemIndicadores",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_1.protos.PpgRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_1.protos.PpgRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_1.protos.PpgResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_1.protos.PpgResponse.deserialize(new Uint8Array(bytes))
            },
            ObtemBancas: {
                path: "/protos.PPG/ObtemBancas",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_1.protos.PpgRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_1.protos.PpgRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_1.protos.PpgResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_1.protos.PpgResponse.deserialize(new Uint8Array(bytes))
            },
            ObtemDocentes: {
                path: "/protos.PPG/ObtemDocentes",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_1.protos.PpgRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_1.protos.PpgRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_1.protos.PpgResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_1.protos.PpgResponse.deserialize(new Uint8Array(bytes))
            },
            ObtemEgressos: {
                path: "/protos.PPG/ObtemEgressos",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_1.protos.PpgRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_1.protos.PpgRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_1.protos.PpgResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_1.protos.PpgResponse.deserialize(new Uint8Array(bytes))
            },
            ObtemProjetos: {
                path: "/protos.PPG/ObtemProjetos",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_1.protos.PpgRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_1.protos.PpgRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_1.protos.PpgResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_1.protos.PpgResponse.deserialize(new Uint8Array(bytes))
            }
        };
        [method: string]: grpc_1.UntypedHandleCall;
        abstract ObtemInformacaoPPG(call: grpc_1.ServerUnaryCall<dependency_1.protos.PpgRequest, dependency_1.protos.PpgResponse>, callback: grpc_1.sendUnaryData<dependency_1.protos.PpgResponse>): void;
        abstract ObtemIndicadores(call: grpc_1.ServerUnaryCall<dependency_1.protos.PpgRequest, dependency_1.protos.PpgResponse>, callback: grpc_1.sendUnaryData<dependency_1.protos.PpgResponse>): void;
        abstract ObtemBancas(call: grpc_1.ServerUnaryCall<dependency_1.protos.PpgRequest, dependency_1.protos.PpgResponse>, callback: grpc_1.sendUnaryData<dependency_1.protos.PpgResponse>): void;
        abstract ObtemDocentes(call: grpc_1.ServerUnaryCall<dependency_1.protos.PpgRequest, dependency_1.protos.PpgResponse>, callback: grpc_1.sendUnaryData<dependency_1.protos.PpgResponse>): void;
        abstract ObtemEgressos(call: grpc_1.ServerUnaryCall<dependency_1.protos.PpgRequest, dependency_1.protos.PpgResponse>, callback: grpc_1.sendUnaryData<dependency_1.protos.PpgResponse>): void;
        abstract ObtemProjetos(call: grpc_1.ServerUnaryCall<dependency_1.protos.PpgRequest, dependency_1.protos.PpgResponse>, callback: grpc_1.sendUnaryData<dependency_1.protos.PpgResponse>): void;
    }
    export class PPGClient extends grpc_1.makeGenericClientConstructor(UnimplementedPPGService.definition, "PPG", {}) {
        constructor(address: string, credentials: grpc_1.ChannelCredentials, options?: Partial<grpc_1.ChannelOptions>) {
            super(address, credentials, options);
        }
        ObtemInformacaoPPG: GrpcUnaryServiceInterface<dependency_1.protos.PpgRequest, dependency_1.protos.PpgResponse> = (message: dependency_1.protos.PpgRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.protos.PpgResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.protos.PpgResponse>, callback?: grpc_1.requestCallback<dependency_1.protos.PpgResponse>): grpc_1.ClientUnaryCall => {
            return super.ObtemInformacaoPPG(message, metadata, options, callback);
        };
        ObtemIndicadores: GrpcUnaryServiceInterface<dependency_1.protos.PpgRequest, dependency_1.protos.PpgResponse> = (message: dependency_1.protos.PpgRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.protos.PpgResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.protos.PpgResponse>, callback?: grpc_1.requestCallback<dependency_1.protos.PpgResponse>): grpc_1.ClientUnaryCall => {
            return super.ObtemIndicadores(message, metadata, options, callback);
        };
        ObtemBancas: GrpcUnaryServiceInterface<dependency_1.protos.PpgRequest, dependency_1.protos.PpgResponse> = (message: dependency_1.protos.PpgRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.protos.PpgResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.protos.PpgResponse>, callback?: grpc_1.requestCallback<dependency_1.protos.PpgResponse>): grpc_1.ClientUnaryCall => {
            return super.ObtemBancas(message, metadata, options, callback);
        };
        ObtemDocentes: GrpcUnaryServiceInterface<dependency_1.protos.PpgRequest, dependency_1.protos.PpgResponse> = (message: dependency_1.protos.PpgRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.protos.PpgResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.protos.PpgResponse>, callback?: grpc_1.requestCallback<dependency_1.protos.PpgResponse>): grpc_1.ClientUnaryCall => {
            return super.ObtemDocentes(message, metadata, options, callback);
        };
        ObtemEgressos: GrpcUnaryServiceInterface<dependency_1.protos.PpgRequest, dependency_1.protos.PpgResponse> = (message: dependency_1.protos.PpgRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.protos.PpgResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.protos.PpgResponse>, callback?: grpc_1.requestCallback<dependency_1.protos.PpgResponse>): grpc_1.ClientUnaryCall => {
            return super.ObtemEgressos(message, metadata, options, callback);
        };
        ObtemProjetos: GrpcUnaryServiceInterface<dependency_1.protos.PpgRequest, dependency_1.protos.PpgResponse> = (message: dependency_1.protos.PpgRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.protos.PpgResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.protos.PpgResponse>, callback?: grpc_1.requestCallback<dependency_1.protos.PpgResponse>): grpc_1.ClientUnaryCall => {
            return super.ObtemProjetos(message, metadata, options, callback);
        };
    }
    export abstract class UnimplementedHomeService {
        static definition = {
            ObtemHome: {
                path: "/protos.Home/ObtemHome",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_1.protos.PpgRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_1.protos.PpgRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_1.protos.PpgResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_1.protos.PpgResponse.deserialize(new Uint8Array(bytes))
            }
        };
        [method: string]: grpc_1.UntypedHandleCall;
        abstract ObtemHome(call: grpc_1.ServerUnaryCall<dependency_1.protos.PpgRequest, dependency_1.protos.PpgResponse>, callback: grpc_1.sendUnaryData<dependency_1.protos.PpgResponse>): void;
    }
    export class HomeClient extends grpc_1.makeGenericClientConstructor(UnimplementedHomeService.definition, "Home", {}) {
        constructor(address: string, credentials: grpc_1.ChannelCredentials, options?: Partial<grpc_1.ChannelOptions>) {
            super(address, credentials, options);
        }
        ObtemHome: GrpcUnaryServiceInterface<dependency_1.protos.PpgRequest, dependency_1.protos.PpgResponse> = (message: dependency_1.protos.PpgRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.protos.PpgResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.protos.PpgResponse>, callback?: grpc_1.requestCallback<dependency_1.protos.PpgResponse>): grpc_1.ClientUnaryCall => {
            return super.ObtemHome(message, metadata, options, callback);
        };
    }
}
