/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 4.25.5
 * source: ppgls.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./messages";
import * as grpc_1 from "@grpc/grpc-js";
export namespace protos {
    interface GrpcUnaryServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, metadata: grpc_1.Metadata, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
    }
    interface GrpcStreamServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): grpc_1.ClientReadableStream<R>;
        (message: P, options?: grpc_1.CallOptions): grpc_1.ClientReadableStream<R>;
    }
    interface GrpWritableServiceInterface<P, R> {
        (metadata: grpc_1.Metadata, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (metadata: grpc_1.Metadata, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
    }
    interface GrpcChunkServiceInterface<P, R> {
        (metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): grpc_1.ClientDuplexStream<P, R>;
        (options?: grpc_1.CallOptions): grpc_1.ClientDuplexStream<P, R>;
    }
    interface GrpcPromiseServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): Promise<R>;
        (message: P, options?: grpc_1.CallOptions): Promise<R>;
    }
    export abstract class UnimplementedIndicadoresPosGraduacaoLSService {
        static definition = {
            GetAbaIndicadoresCurso: {
                path: "/protos.IndicadoresPosGraduacaoLS/GetAbaIndicadoresCurso",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_1.protos.PPGLSRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_1.protos.PPGLSRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_1.protos.PPGLSResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_1.protos.PPGLSResponse.deserialize(new Uint8Array(bytes))
            },
            GetAbaDisciplinas: {
                path: "/protos.IndicadoresPosGraduacaoLS/GetAbaDisciplinas",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_1.protos.PPGLSRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_1.protos.PPGLSRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_1.protos.PPGLSResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_1.protos.PPGLSResponse.deserialize(new Uint8Array(bytes))
            },
            GetAbaRegressos: {
                path: "/protos.IndicadoresPosGraduacaoLS/GetAbaRegressos",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_1.protos.PPGLSRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_1.protos.PPGLSRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_1.protos.PPGLSResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_1.protos.PPGLSResponse.deserialize(new Uint8Array(bytes))
            },
            GetAbaProfessores: {
                path: "/protos.IndicadoresPosGraduacaoLS/GetAbaProfessores",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_1.protos.PPGLSRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_1.protos.PPGLSRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_1.protos.PPGLSResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_1.protos.PPGLSResponse.deserialize(new Uint8Array(bytes))
            },
            GetIndicadoresDisciplina: {
                path: "/protos.IndicadoresPosGraduacaoLS/GetIndicadoresDisciplina",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_1.protos.PPGLSRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_1.protos.PPGLSRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_1.protos.PPGLSResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_1.protos.PPGLSResponse.deserialize(new Uint8Array(bytes))
            },
            GetIndicadoresGlobais: {
                path: "/protos.IndicadoresPosGraduacaoLS/GetIndicadoresGlobais",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_1.protos.PPGLSRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_1.protos.PPGLSRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_1.protos.PPGLSResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_1.protos.PPGLSResponse.deserialize(new Uint8Array(bytes))
            }
        };
        [method: string]: grpc_1.UntypedHandleCall;
        abstract GetAbaIndicadoresCurso(call: grpc_1.ServerUnaryCall<dependency_1.protos.PPGLSRequest, dependency_1.protos.PPGLSResponse>, callback: grpc_1.sendUnaryData<dependency_1.protos.PPGLSResponse>): void;
        abstract GetAbaDisciplinas(call: grpc_1.ServerUnaryCall<dependency_1.protos.PPGLSRequest, dependency_1.protos.PPGLSResponse>, callback: grpc_1.sendUnaryData<dependency_1.protos.PPGLSResponse>): void;
        abstract GetAbaRegressos(call: grpc_1.ServerUnaryCall<dependency_1.protos.PPGLSRequest, dependency_1.protos.PPGLSResponse>, callback: grpc_1.sendUnaryData<dependency_1.protos.PPGLSResponse>): void;
        abstract GetAbaProfessores(call: grpc_1.ServerUnaryCall<dependency_1.protos.PPGLSRequest, dependency_1.protos.PPGLSResponse>, callback: grpc_1.sendUnaryData<dependency_1.protos.PPGLSResponse>): void;
        abstract GetIndicadoresDisciplina(call: grpc_1.ServerUnaryCall<dependency_1.protos.PPGLSRequest, dependency_1.protos.PPGLSResponse>, callback: grpc_1.sendUnaryData<dependency_1.protos.PPGLSResponse>): void;
        abstract GetIndicadoresGlobais(call: grpc_1.ServerUnaryCall<dependency_1.protos.PPGLSRequest, dependency_1.protos.PPGLSResponse>, callback: grpc_1.sendUnaryData<dependency_1.protos.PPGLSResponse>): void;
    }
    export class IndicadoresPosGraduacaoLSClient extends grpc_1.makeGenericClientConstructor(UnimplementedIndicadoresPosGraduacaoLSService.definition, "IndicadoresPosGraduacaoLS", {}) {
        constructor(address: string, credentials: grpc_1.ChannelCredentials, options?: Partial<grpc_1.ChannelOptions>) {
            super(address, credentials, options);
        }
        GetAbaIndicadoresCurso: GrpcUnaryServiceInterface<dependency_1.protos.PPGLSRequest, dependency_1.protos.PPGLSResponse> = (message: dependency_1.protos.PPGLSRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.protos.PPGLSResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.protos.PPGLSResponse>, callback?: grpc_1.requestCallback<dependency_1.protos.PPGLSResponse>): grpc_1.ClientUnaryCall => {
            return super.GetAbaIndicadoresCurso(message, metadata, options, callback);
        };
        GetAbaDisciplinas: GrpcUnaryServiceInterface<dependency_1.protos.PPGLSRequest, dependency_1.protos.PPGLSResponse> = (message: dependency_1.protos.PPGLSRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.protos.PPGLSResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.protos.PPGLSResponse>, callback?: grpc_1.requestCallback<dependency_1.protos.PPGLSResponse>): grpc_1.ClientUnaryCall => {
            return super.GetAbaDisciplinas(message, metadata, options, callback);
        };
        GetAbaRegressos: GrpcUnaryServiceInterface<dependency_1.protos.PPGLSRequest, dependency_1.protos.PPGLSResponse> = (message: dependency_1.protos.PPGLSRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.protos.PPGLSResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.protos.PPGLSResponse>, callback?: grpc_1.requestCallback<dependency_1.protos.PPGLSResponse>): grpc_1.ClientUnaryCall => {
            return super.GetAbaRegressos(message, metadata, options, callback);
        };
        GetAbaProfessores: GrpcUnaryServiceInterface<dependency_1.protos.PPGLSRequest, dependency_1.protos.PPGLSResponse> = (message: dependency_1.protos.PPGLSRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.protos.PPGLSResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.protos.PPGLSResponse>, callback?: grpc_1.requestCallback<dependency_1.protos.PPGLSResponse>): grpc_1.ClientUnaryCall => {
            return super.GetAbaProfessores(message, metadata, options, callback);
        };
        GetIndicadoresDisciplina: GrpcUnaryServiceInterface<dependency_1.protos.PPGLSRequest, dependency_1.protos.PPGLSResponse> = (message: dependency_1.protos.PPGLSRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.protos.PPGLSResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.protos.PPGLSResponse>, callback?: grpc_1.requestCallback<dependency_1.protos.PPGLSResponse>): grpc_1.ClientUnaryCall => {
            return super.GetIndicadoresDisciplina(message, metadata, options, callback);
        };
        GetIndicadoresGlobais: GrpcUnaryServiceInterface<dependency_1.protos.PPGLSRequest, dependency_1.protos.PPGLSResponse> = (message: dependency_1.protos.PPGLSRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.protos.PPGLSResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.protos.PPGLSResponse>, callback?: grpc_1.requestCallback<dependency_1.protos.PPGLSResponse>): grpc_1.ClientUnaryCall => {
            return super.GetIndicadoresGlobais(message, metadata, options, callback);
        };
    }
    export abstract class UnimplementedDadosFormularioPosGraduacaoLSService {
        static definition = {
            GetIndicadoresFormulario: {
                path: "/protos.DadosFormularioPosGraduacaoLS/GetIndicadoresFormulario",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_1.protos.FormularioIndicadoresRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_1.protos.FormularioIndicadoresRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_1.protos.FormularioPPGLSResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_1.protos.FormularioPPGLSResponse.deserialize(new Uint8Array(bytes))
            },
            SearchRegistrosFormualario: {
                path: "/protos.DadosFormularioPosGraduacaoLS/SearchRegistrosFormualario",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_1.protos.FormularioSerchPPGLSRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_1.protos.FormularioSerchPPGLSRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_1.protos.FormularioPPGLSResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_1.protos.FormularioPPGLSResponse.deserialize(new Uint8Array(bytes))
            },
            InsertFormulario: {
                path: "/protos.DadosFormularioPosGraduacaoLS/InsertFormulario",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_1.protos.FormularioPPGLSRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_1.protos.FormularioPPGLSRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_1.protos.FormularioPPGLSResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_1.protos.FormularioPPGLSResponse.deserialize(new Uint8Array(bytes))
            },
            UpdateFormulario: {
                path: "/protos.DadosFormularioPosGraduacaoLS/UpdateFormulario",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_1.protos.FormularioPPGLSRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_1.protos.FormularioPPGLSRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_1.protos.FormularioPPGLSResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_1.protos.FormularioPPGLSResponse.deserialize(new Uint8Array(bytes))
            },
            DeleteFormulario: {
                path: "/protos.DadosFormularioPosGraduacaoLS/DeleteFormulario",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_1.protos.FormularioIndicadoresRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_1.protos.FormularioIndicadoresRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_1.protos.FormularioPPGLSResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_1.protos.FormularioPPGLSResponse.deserialize(new Uint8Array(bytes))
            }
        };
        [method: string]: grpc_1.UntypedHandleCall;
        abstract GetIndicadoresFormulario(call: grpc_1.ServerUnaryCall<dependency_1.protos.FormularioIndicadoresRequest, dependency_1.protos.FormularioPPGLSResponse>, callback: grpc_1.sendUnaryData<dependency_1.protos.FormularioPPGLSResponse>): void;
        abstract SearchRegistrosFormualario(call: grpc_1.ServerUnaryCall<dependency_1.protos.FormularioSerchPPGLSRequest, dependency_1.protos.FormularioPPGLSResponse>, callback: grpc_1.sendUnaryData<dependency_1.protos.FormularioPPGLSResponse>): void;
        abstract InsertFormulario(call: grpc_1.ServerUnaryCall<dependency_1.protos.FormularioPPGLSRequest, dependency_1.protos.FormularioPPGLSResponse>, callback: grpc_1.sendUnaryData<dependency_1.protos.FormularioPPGLSResponse>): void;
        abstract UpdateFormulario(call: grpc_1.ServerUnaryCall<dependency_1.protos.FormularioPPGLSRequest, dependency_1.protos.FormularioPPGLSResponse>, callback: grpc_1.sendUnaryData<dependency_1.protos.FormularioPPGLSResponse>): void;
        abstract DeleteFormulario(call: grpc_1.ServerUnaryCall<dependency_1.protos.FormularioIndicadoresRequest, dependency_1.protos.FormularioPPGLSResponse>, callback: grpc_1.sendUnaryData<dependency_1.protos.FormularioPPGLSResponse>): void;
    }
    export class DadosFormularioPosGraduacaoLSClient extends grpc_1.makeGenericClientConstructor(UnimplementedDadosFormularioPosGraduacaoLSService.definition, "DadosFormularioPosGraduacaoLS", {}) {
        constructor(address: string, credentials: grpc_1.ChannelCredentials, options?: Partial<grpc_1.ChannelOptions>) {
            super(address, credentials, options);
        }
        GetIndicadoresFormulario: GrpcUnaryServiceInterface<dependency_1.protos.FormularioIndicadoresRequest, dependency_1.protos.FormularioPPGLSResponse> = (message: dependency_1.protos.FormularioIndicadoresRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.protos.FormularioPPGLSResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.protos.FormularioPPGLSResponse>, callback?: grpc_1.requestCallback<dependency_1.protos.FormularioPPGLSResponse>): grpc_1.ClientUnaryCall => {
            return super.GetIndicadoresFormulario(message, metadata, options, callback);
        };
        SearchRegistrosFormualario: GrpcUnaryServiceInterface<dependency_1.protos.FormularioSerchPPGLSRequest, dependency_1.protos.FormularioPPGLSResponse> = (message: dependency_1.protos.FormularioSerchPPGLSRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.protos.FormularioPPGLSResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.protos.FormularioPPGLSResponse>, callback?: grpc_1.requestCallback<dependency_1.protos.FormularioPPGLSResponse>): grpc_1.ClientUnaryCall => {
            return super.SearchRegistrosFormualario(message, metadata, options, callback);
        };
        InsertFormulario: GrpcUnaryServiceInterface<dependency_1.protos.FormularioPPGLSRequest, dependency_1.protos.FormularioPPGLSResponse> = (message: dependency_1.protos.FormularioPPGLSRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.protos.FormularioPPGLSResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.protos.FormularioPPGLSResponse>, callback?: grpc_1.requestCallback<dependency_1.protos.FormularioPPGLSResponse>): grpc_1.ClientUnaryCall => {
            return super.InsertFormulario(message, metadata, options, callback);
        };
        UpdateFormulario: GrpcUnaryServiceInterface<dependency_1.protos.FormularioPPGLSRequest, dependency_1.protos.FormularioPPGLSResponse> = (message: dependency_1.protos.FormularioPPGLSRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.protos.FormularioPPGLSResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.protos.FormularioPPGLSResponse>, callback?: grpc_1.requestCallback<dependency_1.protos.FormularioPPGLSResponse>): grpc_1.ClientUnaryCall => {
            return super.UpdateFormulario(message, metadata, options, callback);
        };
        DeleteFormulario: GrpcUnaryServiceInterface<dependency_1.protos.FormularioIndicadoresRequest, dependency_1.protos.FormularioPPGLSResponse> = (message: dependency_1.protos.FormularioIndicadoresRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.protos.FormularioPPGLSResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.protos.FormularioPPGLSResponse>, callback?: grpc_1.requestCallback<dependency_1.protos.FormularioPPGLSResponse>): grpc_1.ClientUnaryCall => {
            return super.DeleteFormulario(message, metadata, options, callback);
        };
    }
    export abstract class UnimplementedDadosPosGraduacaoLSService {
        static definition = {
            GetCursos: {
                path: "/protos.DadosPosGraduacaoLS/GetCursos",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_1.protos.PPGLSRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_1.protos.PPGLSRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_1.protos.PPGLSResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_1.protos.PPGLSResponse.deserialize(new Uint8Array(bytes))
            },
            GetCurso: {
                path: "/protos.DadosPosGraduacaoLS/GetCurso",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_1.protos.PPGLSRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_1.protos.PPGLSRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_1.protos.PPGLSResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_1.protos.PPGLSResponse.deserialize(new Uint8Array(bytes))
            },
            GetDisciplinas: {
                path: "/protos.DadosPosGraduacaoLS/GetDisciplinas",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_1.protos.PPGLSRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_1.protos.PPGLSRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_1.protos.PPGLSResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_1.protos.PPGLSResponse.deserialize(new Uint8Array(bytes))
            },
            GetDisciplina: {
                path: "/protos.DadosPosGraduacaoLS/GetDisciplina",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_1.protos.PPGLSRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_1.protos.PPGLSRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_1.protos.PPGLSResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_1.protos.PPGLSResponse.deserialize(new Uint8Array(bytes))
            }
        };
        [method: string]: grpc_1.UntypedHandleCall;
        abstract GetCursos(call: grpc_1.ServerUnaryCall<dependency_1.protos.PPGLSRequest, dependency_1.protos.PPGLSResponse>, callback: grpc_1.sendUnaryData<dependency_1.protos.PPGLSResponse>): void;
        abstract GetCurso(call: grpc_1.ServerUnaryCall<dependency_1.protos.PPGLSRequest, dependency_1.protos.PPGLSResponse>, callback: grpc_1.sendUnaryData<dependency_1.protos.PPGLSResponse>): void;
        abstract GetDisciplinas(call: grpc_1.ServerUnaryCall<dependency_1.protos.PPGLSRequest, dependency_1.protos.PPGLSResponse>, callback: grpc_1.sendUnaryData<dependency_1.protos.PPGLSResponse>): void;
        abstract GetDisciplina(call: grpc_1.ServerUnaryCall<dependency_1.protos.PPGLSRequest, dependency_1.protos.PPGLSResponse>, callback: grpc_1.sendUnaryData<dependency_1.protos.PPGLSResponse>): void;
    }
    export class DadosPosGraduacaoLSClient extends grpc_1.makeGenericClientConstructor(UnimplementedDadosPosGraduacaoLSService.definition, "DadosPosGraduacaoLS", {}) {
        constructor(address: string, credentials: grpc_1.ChannelCredentials, options?: Partial<grpc_1.ChannelOptions>) {
            super(address, credentials, options);
        }
        GetCursos: GrpcUnaryServiceInterface<dependency_1.protos.PPGLSRequest, dependency_1.protos.PPGLSResponse> = (message: dependency_1.protos.PPGLSRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.protos.PPGLSResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.protos.PPGLSResponse>, callback?: grpc_1.requestCallback<dependency_1.protos.PPGLSResponse>): grpc_1.ClientUnaryCall => {
            return super.GetCursos(message, metadata, options, callback);
        };
        GetCurso: GrpcUnaryServiceInterface<dependency_1.protos.PPGLSRequest, dependency_1.protos.PPGLSResponse> = (message: dependency_1.protos.PPGLSRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.protos.PPGLSResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.protos.PPGLSResponse>, callback?: grpc_1.requestCallback<dependency_1.protos.PPGLSResponse>): grpc_1.ClientUnaryCall => {
            return super.GetCurso(message, metadata, options, callback);
        };
        GetDisciplinas: GrpcUnaryServiceInterface<dependency_1.protos.PPGLSRequest, dependency_1.protos.PPGLSResponse> = (message: dependency_1.protos.PPGLSRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.protos.PPGLSResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.protos.PPGLSResponse>, callback?: grpc_1.requestCallback<dependency_1.protos.PPGLSResponse>): grpc_1.ClientUnaryCall => {
            return super.GetDisciplinas(message, metadata, options, callback);
        };
        GetDisciplina: GrpcUnaryServiceInterface<dependency_1.protos.PPGLSRequest, dependency_1.protos.PPGLSResponse> = (message: dependency_1.protos.PPGLSRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.protos.PPGLSResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.protos.PPGLSResponse>, callback?: grpc_1.requestCallback<dependency_1.protos.PPGLSResponse>): grpc_1.ClientUnaryCall => {
            return super.GetDisciplina(message, metadata, options, callback);
        };
    }
}
