/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 4.25.5
 * source: usuarios.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./messages";
import * as grpc_1 from "@grpc/grpc-js";
export namespace protos {
    interface GrpcUnaryServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, metadata: grpc_1.Metadata, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
    }
    interface GrpcStreamServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): grpc_1.ClientReadableStream<R>;
        (message: P, options?: grpc_1.CallOptions): grpc_1.ClientReadableStream<R>;
    }
    interface GrpWritableServiceInterface<P, R> {
        (metadata: grpc_1.Metadata, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (metadata: grpc_1.Metadata, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
    }
    interface GrpcChunkServiceInterface<P, R> {
        (metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): grpc_1.ClientDuplexStream<P, R>;
        (options?: grpc_1.CallOptions): grpc_1.ClientDuplexStream<P, R>;
    }
    interface GrpcPromiseServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): Promise<R>;
        (message: P, options?: grpc_1.CallOptions): Promise<R>;
    }
    export abstract class UnimplementedUsuarioService {
        static definition = {
            Login: {
                path: "/protos.Usuario/Login",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_1.protos.LoginRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_1.protos.LoginRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_1.protos.LoginResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_1.protos.LoginResponse.deserialize(new Uint8Array(bytes))
            },
            Logout: {
                path: "/protos.Usuario/Logout",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_1.protos.LogoutRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_1.protos.LogoutRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_1.protos.LogoutResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_1.protos.LogoutResponse.deserialize(new Uint8Array(bytes))
            },
            ObtemUsuario: {
                path: "/protos.Usuario/ObtemUsuario",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: dependency_1.protos.UsuarioRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => dependency_1.protos.UsuarioRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_1.protos.UsuarioResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_1.protos.UsuarioResponse.deserialize(new Uint8Array(bytes))
            }
        };
        [method: string]: grpc_1.UntypedHandleCall;
        abstract Login(call: grpc_1.ServerUnaryCall<dependency_1.protos.LoginRequest, dependency_1.protos.LoginResponse>, callback: grpc_1.sendUnaryData<dependency_1.protos.LoginResponse>): void;
        abstract Logout(call: grpc_1.ServerUnaryCall<dependency_1.protos.LogoutRequest, dependency_1.protos.LogoutResponse>, callback: grpc_1.sendUnaryData<dependency_1.protos.LogoutResponse>): void;
        abstract ObtemUsuario(call: grpc_1.ServerUnaryCall<dependency_1.protos.UsuarioRequest, dependency_1.protos.UsuarioResponse>, callback: grpc_1.sendUnaryData<dependency_1.protos.UsuarioResponse>): void;
    }
    export class UsuarioClient extends grpc_1.makeGenericClientConstructor(UnimplementedUsuarioService.definition, "Usuario", {}) {
        constructor(address: string, credentials: grpc_1.ChannelCredentials, options?: Partial<grpc_1.ChannelOptions>) {
            super(address, credentials, options);
        }
        Login: GrpcUnaryServiceInterface<dependency_1.protos.LoginRequest, dependency_1.protos.LoginResponse> = (message: dependency_1.protos.LoginRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.protos.LoginResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.protos.LoginResponse>, callback?: grpc_1.requestCallback<dependency_1.protos.LoginResponse>): grpc_1.ClientUnaryCall => {
            return super.Login(message, metadata, options, callback);
        };
        Logout: GrpcUnaryServiceInterface<dependency_1.protos.LogoutRequest, dependency_1.protos.LogoutResponse> = (message: dependency_1.protos.LogoutRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.protos.LogoutResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.protos.LogoutResponse>, callback?: grpc_1.requestCallback<dependency_1.protos.LogoutResponse>): grpc_1.ClientUnaryCall => {
            return super.Logout(message, metadata, options, callback);
        };
        ObtemUsuario: GrpcUnaryServiceInterface<dependency_1.protos.UsuarioRequest, dependency_1.protos.UsuarioResponse> = (message: dependency_1.protos.UsuarioRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.protos.UsuarioResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.protos.UsuarioResponse>, callback?: grpc_1.requestCallback<dependency_1.protos.UsuarioResponse>): grpc_1.ClientUnaryCall => {
            return super.ObtemUsuario(message, metadata, options, callback);
        };
    }
}
